chore: debug
Signed-off-by: blam <ben@blam.sh>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -73,31 +73,31 @@ jobs:
           registry-url: https://registry.npmjs.org/ # Needed for auth
 
       # Cache every node_modules folder inside the monorepo
-      # - name: cache all node_modules
-      #   id: cache-modules
-      #   uses: actions/cache@v2
-      #   with:
-      #     path: '**/node_modules'
-      #     # We use both yarn.lock and package.json as cache keys to ensure that
-      #     # changes to local monorepo packages bust the cache.
-      #     key: ${{ runner.os }}-v${{ matrix.node-version }}-node_modules-${{ hashFiles('yarn.lock', '**/package.json') }}
+      - name: cache all node_modules
+        id: cache-modules
+        uses: actions/cache@v2
+        with:
+          path: '**/node_modules'
+          # We use both yarn.lock and package.json as cache keys to ensure that
+          # changes to local monorepo packages bust the cache.
+          key: ${{ runner.os }}-v${{ matrix.node-version }}-node_modules-${{ hashFiles('yarn.lock', '**/package.json') }}
 
       # If we get a cache hit for node_modules, there's no need to bring in the global
       # yarn cache or run yarn install, as all dependencies will be installed already.
 
-      # - name: find location of global yarn cache
-      #   id: yarn-cache
-      #   if: steps.cache-modules.outputs.cache-hit != 'true'
-      #   run: echo "::set-output name=dir::$(yarn cache dir)"
+      - name: find location of global yarn cache
+        id: yarn-cache
+        if: steps.cache-modules.outputs.cache-hit != 'true'
+        run: echo "::set-output name=dir::$(yarn cache dir)"
 
-      # - name: cache global yarn cache
-      #   uses: actions/cache@v2
-      #   if: steps.cache-modules.outputs.cache-hit != 'true'
-      #   with:
-      #     path: ${{ steps.yarn-cache.outputs.dir }}
-      #     key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
-      #     restore-keys: |
-      #       ${{ runner.os }}-yarn-
+      - name: cache global yarn cache
+        uses: actions/cache@v2
+        if: steps.cache-modules.outputs.cache-hit != 'true'
+        with:
+          path: ${{ steps.yarn-cache.outputs.dir }}
+          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-yarn-
 
       - name: yarn install
         if: steps.cache-modules.outputs.cache-hit != 'true'
@@ -109,82 +109,102 @@ jobs:
         run: git diff --quiet origin/master HEAD -- yarn.lock
         continue-on-error: true
 
-      - name: prettier
-        run: yarn prettier:check
+      # - name: prettier
+      #   run: yarn prettier:check
 
-      - name: lock
-        run: yarn lock:check
+      # - name: lock
+      #   run: yarn lock:check
 
-      - name: validate config
-        run: yarn backstage-cli config:check --lax
+      # - name: validate config
+      #   run: yarn backstage-cli config:check --lax
 
-      - name: lint
-        run: yarn backstage-cli repo lint --since origin/master
+      # - name: lint
+      #   run: yarn backstage-cli repo lint --since origin/master
 
-      - name: type checking and declarations
-        run: yarn tsc:full
+      # - name: type checking and declarations
+      #   run: yarn tsc:full
 
-        # We need to generate the API references as well, so that we can verify the doc links
-      - name: check api reports and generate API reference
-        run: yarn build:api-reports:only --ci --docs
+      #   # We need to generate the API references as well, so that we can verify the doc links
+      # - name: check api reports and generate API reference
+      #   run: yarn build:api-reports:only --ci --docs
 
-      - name: verify api reference
-        run: node scripts/verify-api-reference.js
+      # - name: verify api reference
+      #   run: node scripts/verify-api-reference.js
 
-      - name: verify changesets
-        run: node scripts/verify-changesets.js
+      # - name: verify changesets
+      #   run: node scripts/verify-changesets.js
 
-      - name: verify doc links
-        run: node scripts/verify-links.js
+      # - name: verify doc links
+      #   run: node scripts/verify-links.js
 
-      - name: verify local dependency ranges
-        run: node scripts/verify-local-dependencies.js
+      # - name: verify local dependency ranges
+      #   run: node scripts/verify-local-dependencies.js
 
-      - name: build changed packages
-        if: ${{ steps.yarn-lock.outcome == 'success' }}
-        run: yarn backstage-cli repo build --all --since origin/master
+      # - name: build changed packages
+      #   if: ${{ steps.yarn-lock.outcome == 'success' }}
+      #   run: yarn backstage-cli repo build --all --since origin/master
 
-      - name: build all packages
-        if: ${{ steps.yarn-lock.outcome == 'failure' }}
-        run: yarn backstage-cli repo build --all
+      # - name: build all packages
+      #   if: ${{ steps.yarn-lock.outcome == 'failure' }}
+      #   run: yarn backstage-cli repo build --all
 
-      - name: verify type dependencies
-        run: yarn lint:type-deps
+      # - name: verify type dependencies
+      #   run: yarn lint:type-deps
 
-      - name: test changed packages
-        if: ${{ steps.yarn-lock.outcome == 'success' }}
-        run: yarn lerna -- run test --since origin/master -- --coverage --runInBand
+      # - name: test changed packages
+      #   if: ${{ steps.yarn-lock.outcome == 'success' }}
+      #   run: yarn lerna -- run test --since origin/master -- --coverage --runInBand
+      #   env:
+      #     BACKSTAGE_NEXT_TESTS: 1
+      #     BACKSTAGE_TEST_DISABLE_DOCKER: 1
+      #     BACKSTAGE_TEST_DATABASE_POSTGRES13_CONNECTION_STRING: postgresql://postgres:postgres@localhost:${{ job.services.postgres13.ports[5432] }}
+      #     BACKSTAGE_TEST_DATABASE_POSTGRES9_CONNECTION_STRING: postgresql://postgres:postgres@localhost:${{ job.services.postgres9.ports[5432] }}
+      #     BACKSTAGE_TEST_DATABASE_MYSQL8_CONNECTION_STRING: mysql://root:root@localhost:${{ job.services.mysql8.ports[3306] }}/ignored
+
+      # - name: test all packages (and upload coverage)
+      #   if: ${{ steps.yarn-lock.outcome == 'failure' }}
+      #   run: |
+      #     yarn lerna -- run test -- --coverage --runInBand
+      #     bash <(curl -s https://codecov.io/bash) -N $(git rev-parse FETCH_HEAD)
+      #   env:
+      #     BACKSTAGE_NEXT_TESTS: 1
+      #     BACKSTAGE_TEST_DISABLE_DOCKER: 1
+      #     BACKSTAGE_TEST_DATABASE_POSTGRES13_CONNECTION_STRING: postgresql://postgres:postgres@localhost:${{ job.services.postgres13.ports[5432] }}
+      #     BACKSTAGE_TEST_DATABASE_POSTGRES9_CONNECTION_STRING: postgresql://postgres:postgres@localhost:${{ job.services.postgres9.ports[5432] }}
+      #     BACKSTAGE_TEST_DATABASE_MYSQL8_CONNECTION_STRING: mysql://root:root@localhost:${{ job.services.mysql8.ports[3306] }}/ignored
+
+      # - name: verify plugin template
+      #   run: yarn lerna -- run diff -- --check
+
+      # - name: ensure clean working directory
+      #   run: |
+      #     if files=$(git ls-files --exclude-standard --others --modified) && [[ -z "$files" ]]; then
+      #       exit 0
+      #     else
+      #       echo ""
+      #       echo "Working directory has been modified:"
+      #       echo ""
+      #       git status --short
+      #       echo ""
+      #       exit 1
+      #     fi
+
+      - name: run test
+        run: yarn test packages/catalog-client/src/CatalogClient.test.ts
         env:
-          BACKSTAGE_NEXT_TESTS: 1
-          BACKSTAGE_TEST_DISABLE_DOCKER: 1
-          BACKSTAGE_TEST_DATABASE_POSTGRES13_CONNECTION_STRING: postgresql://postgres:postgres@localhost:${{ job.services.postgres13.ports[5432] }}
-          BACKSTAGE_TEST_DATABASE_POSTGRES9_CONNECTION_STRING: postgresql://postgres:postgres@localhost:${{ job.services.postgres9.ports[5432] }}
-          BACKSTAGE_TEST_DATABASE_MYSQL8_CONNECTION_STRING: mysql://root:root@localhost:${{ job.services.mysql8.ports[3306] }}/ignored
+          DEBUG: '*'
 
-      - name: test all packages (and upload coverage)
-        if: ${{ steps.yarn-lock.outcome == 'failure' }}
-        run: |
-          yarn lerna -- run test -- --coverage --runInBand
-          bash <(curl -s https://codecov.io/bash) -N $(git rev-parse FETCH_HEAD)
+      - name: run test
+        run: yarn test packages/catalog-client/src/CatalogClient.test.ts
         env:
-          BACKSTAGE_NEXT_TESTS: 1
-          BACKSTAGE_TEST_DISABLE_DOCKER: 1
-          BACKSTAGE_TEST_DATABASE_POSTGRES13_CONNECTION_STRING: postgresql://postgres:postgres@localhost:${{ job.services.postgres13.ports[5432] }}
-          BACKSTAGE_TEST_DATABASE_POSTGRES9_CONNECTION_STRING: postgresql://postgres:postgres@localhost:${{ job.services.postgres9.ports[5432] }}
-          BACKSTAGE_TEST_DATABASE_MYSQL8_CONNECTION_STRING: mysql://root:root@localhost:${{ job.services.mysql8.ports[3306] }}/ignored
+          DEBUG: '*'
 
-      - name: verify plugin template
-        run: yarn lerna -- run diff -- --check
+      - name: run test
+        run: yarn test packages/catalog-client/src/CatalogClient.test.ts
+        env:
+          DEBUG: '*'
 
-      - name: ensure clean working directory
-        run: |
-          if files=$(git ls-files --exclude-standard --others --modified) && [[ -z "$files" ]]; then
-            exit 0
-          else
-            echo ""
-            echo "Working directory has been modified:"
-            echo ""
-            git status --short
-            echo ""
-            exit 1
-          fi
+      - name: run test
+        run: yarn test packages/catalog-client/src/CatalogClient.test.ts
+        env:
+          DEBUG: '*'
